// ─── EPOCH: Sunday Feb 22 2026 = "week 1" start ───────────────────────────────
export const EPOCH_STR = "2026-02-22";

export const DEFAULT_SCHEDULE = [
  // DAILY
  {id:"d1",  task:"Load/unload dishwasher or wash dishes",           cat:"Kitchen",  freq:"daily"},
  {id:"d2",  task:"Sweep kitchen floors & entryway",                 cat:"Floors",   freq:"daily"},
  {id:"d3",  task:"Vacuum carpet around litter box",                 cat:"Litter",   freq:"daily"},
  {id:"d4",  task:"Wipe down bathroom counters & sink",              cat:"Bathroom", freq:"daily"},
  {id:"d5",  task:"Wash cat food bowls",                             cat:"Litter",   freq:"daily"},
  {id:"d6",  task:"Replace cat water",                               cat:"Litter",   freq:"daily"},
  {id:"d7",  task:"Scoop litter",                                    cat:"Litter",   freq:"daily"},
  {id:"d8",  task:"Make bed",                                        cat:"Bedroom",  freq:"daily"},
  {id:"d9",  task:"Wipe down dining table",                          cat:"Misc",     freq:"daily"},
  {id:"d10", task:"Wipe crumbs from kitchen counters",               cat:"Kitchen",  freq:"daily"},
  {id:"d11", task:"Rinse food from kitchen sink",                    cat:"Kitchen",  freq:"daily"},
  {id:"d12", task:"Wipe crumbs from stove",                          cat:"Kitchen",  freq:"daily"},
  {id:"d13", task:"Rinse out coffee carafe & filter basket",         cat:"Kitchen",  freq:"daily"},
  {id:"d14", task:"Pick up clutter",                                 cat:"Misc",     freq:"daily"},
  // EVERY 3 DAYS
  {id:"e3d1",task:"Disinfect sponge (run through dishwasher)",       cat:"Kitchen",  freq:"3day",      lastDone:"2026-02-18"},
  // WEEKLY — SUNDAY
  {id:"ws1", task:"Wash/change bed sheets",                          cat:"Bedroom",  freq:"weekly", dow:0, lastDone:"2026-02-15"},
  {id:"ws2", task:"Dust all lamps",                                  cat:"Bedroom",  freq:"weekly", dow:0, lastDone:"2026-02-16"},
  {id:"ws3", task:"Wipe down dresser (sides & front)",               cat:"Bedroom",  freq:"weekly", dow:0, lastDone:"2026-02-16"},
  {id:"ws4", task:"Dust jewelry, perfume & bedroom trinkets",        cat:"Bedroom",  freq:"weekly", dow:0, lastDone:"2026-02-16"},
  {id:"ws5", task:"Wipe down wooden side tables, coffee table books, record player & records", cat:"Misc", freq:"weekly", dow:0, lastDone:"2026-02-16"},
  {id:"ws6", task:"Clean mirrors (large + hallway)",                 cat:"Misc",     freq:"weekly", dow:0, lastDone:"2026-02-16"},
  {id:"ws7", task:"Wipe down/vacuum living room cabinet",            cat:"Shelving", freq:"weekly", dow:0, lastDone:"2026-02-06"},
  {id:"ws8", task:"Wipe down bedroom shelf",                         cat:"Shelving", freq:"weekly", dow:0, lastDone:"2026-02-06"},
  {id:"ws9", task:"Wipe down/dust TV room shelf by window",          cat:"Shelving", freq:"weekly", dow:0, lastDone:"2026-02-07"},
  // WEEKLY — MONDAY
  {id:"wm1", task:"Deep clean toilet (interior & exterior)",         cat:"Bathroom", freq:"weekly", dow:1, lastDone:"2026-02-16"},
  {id:"wm2", task:"Disinfect toilet brush & holder",                 cat:"Bathroom", freq:"weekly", dow:1, lastDone:"2026-02-16"},
  {id:"wm3", task:"Spray/wipe down shower walls & tub",              cat:"Bathroom", freq:"weekly", dow:1, lastDone:null},
  {id:"wm4", task:"Polish chrome shower fixtures",                   cat:"Bathroom", freq:"weekly", dow:1, lastDone:null},
  {id:"wm5", task:"Dust bathroom surfaces & all trinkets",           cat:"Bathroom", freq:"weekly", dow:1, lastDone:"2026-02-16"},
  {id:"wm6", task:"Deep clean bathroom counters",                    cat:"Bathroom", freq:"weekly", dow:1, lastDone:"2026-02-16"},
  {id:"wm7", task:"Deep clean bathroom sink",                        cat:"Bathroom", freq:"weekly", dow:1, lastDone:"2026-02-16"},
  {id:"wm8", task:"Polish bathroom faucet, handle & drain",          cat:"Bathroom", freq:"weekly", dow:1, lastDone:"2026-02-16"},
  {id:"wm9", task:"Polish bathroom mirrors",                         cat:"Bathroom", freq:"weekly", dow:1, lastDone:"2026-02-16"},
  // WEEKLY — TUESDAY (Kitchen)
  {id:"wt1", task:"Scrub kitchen counters w/ baking soda & soap",   cat:"Kitchen",  freq:"weekly", dow:2, lastDone:null},
  {id:"wt2", task:"Treat counter stains w/ lemon + salt",           cat:"Kitchen",  freq:"weekly", dow:2, lastDone:null},
  {id:"wt3", task:"Scrub kitchen sink basin, drain & faucet",       cat:"Kitchen",  freq:"weekly", dow:2, lastDone:"2026-02-16"},
  {id:"wt4", task:"Run sink drain covers & brushes through dishwasher", cat:"Kitchen", freq:"weekly", dow:2, lastDone:null},
  {id:"wt5", task:"Wash sink blue tray; wipe soap & hand soap bottles", cat:"Kitchen", freq:"weekly", dow:2, lastDone:"2026-02-08"},
  {id:"wt6", task:"Scrub stovetop w/ baking soda & soap",           cat:"Kitchen",  freq:"weekly", dow:2, lastDone:"2026-02-16"},
  {id:"wt7", task:"Wipe stove control panel, top & front edges",    cat:"Kitchen",  freq:"weekly", dow:2, lastDone:"2026-02-04"},
  {id:"wt8", task:"Wipe down range hood exterior",                   cat:"Kitchen",  freq:"weekly", dow:2, lastDone:"2026-02-04"},
  {id:"wt9", task:"Dust kitchen lamp, salt pig, utensil holder, oils, coffee jar, mortar & pestle", cat:"Kitchen", freq:"weekly", dow:2, lastDone:"2026-02-08"},
  {id:"wt10",task:"Wash & dry fruit bowl, wooden stand & spoon rest", cat:"Kitchen", freq:"weekly", dow:2, lastDone:"2026-02-08"},
  {id:"wt11",task:"Clean microwave interior & exterior; wash plate & disc", cat:"Kitchen", freq:"weekly", dow:2, lastDone:"2026-02-10"},
  {id:"wt12",task:"Dust/wipe coffee maker exterior",                 cat:"Kitchen",  freq:"weekly", dow:2, lastDone:"2026-02-14"},
  {id:"wt13",task:"Empty toaster crumb tray; wipe toaster exterior & top", cat:"Kitchen", freq:"weekly", dow:2, lastDone:null},
  // WEEKLY — SATURDAY (Floors + Windows + Litter)
  {id:"wsa1",task:"Thorough vacuum/sweep of whole house",            cat:"Floors",   freq:"weekly", dow:6, lastDone:null},
  {id:"wsa2",task:"Wet mop tile floors",                             cat:"Floors",   freq:"weekly", dow:6, lastDone:null},
  {id:"wsa3",task:"Wipe down front door threshold",                  cat:"Floors",   freq:"weekly", dow:6, lastDone:null},
  {id:"wsa4",task:"Windex interior window/door glass",               cat:"Windows",  freq:"weekly", dow:6, lastDone:null},
  {id:"wsa5",task:"Dust window sills",                               cat:"Windows",  freq:"weekly", dow:6, lastDone:null},
  {id:"wsa6",task:"Top off litter & dust litter box lid/exterior",   cat:"Litter",   freq:"weekly", dow:6, lastDone:"2026-02-19"},
  {id:"wsa7",task:"Wipe down shoe cabinet & trinkets/vase on top",   cat:"Misc",     freq:"weekly", dow:6, lastDone:"2026-02-16"},
  {id:"wsa8",task:"Wipe down TV",                                    cat:"Misc",     freq:"weekly", dow:6, lastDone:"2026-02-16"},
  {id:"wsa9",task:"Wipe down cat scratcher",                         cat:"Litter",   freq:"weekly", dow:6, lastDone:"2026-02-16"},
  // BIWEEKLY — SUNDAY
  {id:"b2s0a",task:"Deep clean living room cabinet",                 cat:"Shelving", freq:"biweekly", dow:0, weekOffset:0, lastDone:"2026-02-06"},
  {id:"b2s0b",task:"Deep clean bedroom shelf & windowsill",          cat:"Shelving", freq:"biweekly", dow:0, weekOffset:0, lastDone:"2026-02-06"},
  {id:"b2s1a",task:"Deep clean TV room shelf by window",             cat:"Shelving", freq:"biweekly", dow:0, weekOffset:1, lastDone:null},
  {id:"b2s1b",task:"Dust shelves & trinkets on TV stand",            cat:"Shelving", freq:"biweekly", dow:0, weekOffset:1, lastDone:"2026-02-07"},
  {id:"b2s1c",task:"Deep vacuum couch/cushions",                     cat:"Misc",     freq:"biweekly", dow:0, weekOffset:1, lastDone:null},
  {id:"b2s1d",task:"Vacuum bar stools & dining chairs",              cat:"Misc",     freq:"biweekly", dow:0, weekOffset:1, lastDone:"2026-02-07"},
  // BIWEEKLY — MONDAY
  {id:"b2m0a",task:"Wipe down outsides of bathroom cabinets/drawers & handles", cat:"Bathroom", freq:"biweekly", dow:1, weekOffset:0, lastDone:null},
  {id:"b2m1a",task:"Dust baseboards (vacuum)",                       cat:"Floors",   freq:"biweekly", dow:1, weekOffset:1, lastDone:"2026-02-07"},
  {id:"b2m1b",task:"Deep clean white area rug (de-lint)",            cat:"Floors",   freq:"biweekly", dow:1, weekOffset:1, lastDone:null},
  // BIWEEKLY — TUESDAY A
  {id:"b2t0a",task:"Disinfect kitchen counters w/ dilute vinegar",   cat:"Kitchen",  freq:"biweekly", dow:2, weekOffset:0, lastDone:null},
  {id:"b2t0b",task:"Moisturize kitchen counters w/ mineral oil",     cat:"Kitchen",  freq:"biweekly", dow:2, weekOffset:0, lastDone:null},
  {id:"b2t0c",task:"Wipe down front of oven & handle w/ baking soda", cat:"Kitchen", freq:"biweekly", dow:2, weekOffset:0, lastDone:"2026-02-04"},
  {id:"b2t0d",task:"Clean stove dials; polish chrome parts of oven & hood", cat:"Kitchen", freq:"biweekly", dow:2, weekOffset:0, lastDone:null},
  // BIWEEKLY — TUESDAY B
  {id:"b2t1a",task:"Clean out fridge & freezer",                     cat:"Kitchen",  freq:"biweekly", dow:2, weekOffset:1, lastDone:"2026-02-17"},
  {id:"b2t1b",task:"Polish exterior of dishwasher",                  cat:"Kitchen",  freq:"biweekly", dow:2, weekOffset:1, lastDone:"2026-02-16"},
  {id:"b2t1c",task:"Polish exterior of kitchen trash can",           cat:"Kitchen",  freq:"biweekly", dow:2, weekOffset:1, lastDone:"2026-02-10"},
  {id:"b2t1d",task:"Wipe kitchen cabinet & drawer doors/handles",    cat:"Kitchen",  freq:"biweekly", dow:2, weekOffset:1, lastDone:null},
  {id:"b2t1e",task:"Wipe cork coasters; deep clean utensil holder",  cat:"Kitchen",  freq:"biweekly", dow:2, weekOffset:1, lastDone:null},
  // BIWEEKLY — THURSDAY
  {id:"b2th0a",task:"Replace litter completely",                     cat:"Litter",   freq:"biweekly", dow:4, weekOffset:0, lastDone:"2026-02-19"},
  {id:"b2th0b",task:"Wash litter box, scoop & holder, and lid",      cat:"Litter",   freq:"biweekly", dow:4, weekOffset:0, lastDone:"2026-02-07"},
  {id:"b2th1a",task:"Sweep deck; dust cobwebs around doors/porch; shake out welcome mat", cat:"Outdoor", freq:"biweekly", dow:4, weekOffset:1, lastDone:null},
  {id:"b2th1b",task:"Wipe down outdoor chairs & tables",             cat:"Outdoor",  freq:"biweekly", dow:4, weekOffset:1, lastDone:null},
  // TRIWEEKLY
  {id:"t3s0", task:"Dust bookshelves & trinkets",                    cat:"Shelving", freq:"triweekly", dow:0, weekOffset:0, lastDone:"2026-02-07"},
  {id:"t3t0a",task:"Deep clean dish soap dispenser; replace sponge", cat:"Kitchen",  freq:"triweekly", dow:2, weekOffset:0, lastDone:"2026-02-08"},
  {id:"t3t0b",task:"Wipe down top & sides of fridge; polish fridge/freezer doors", cat:"Kitchen", freq:"triweekly", dow:2, weekOffset:0, lastDone:"2026-02-10"},
  {id:"t3t1a",task:"Wipe underneath kitchen cabinets",               cat:"Kitchen",  freq:"triweekly", dow:2, weekOffset:1, lastDone:null},
  {id:"t3t1b",task:"Wipe down kitchen backsplash",                   cat:"Kitchen",  freq:"triweekly", dow:2, weekOffset:1, lastDone:null},
  {id:"t3t2a",task:"Thoroughly wash all removable coffee maker parts", cat:"Kitchen", freq:"triweekly", dow:2, weekOffset:2, lastDone:null},
  {id:"t3sa0",task:"Clear out & dust key/wallet holder by door",     cat:"Misc",     freq:"triweekly", dow:6, weekOffset:0, lastDone:"2026-02-07"},
  {id:"t3sa1",task:"Clean coasters",                                 cat:"Misc",     freq:"triweekly", dow:6, weekOffset:1, lastDone:null},
  {id:"t3sa2",task:"Wipe down posters/paintings (living room, bathroom, TV room)", cat:"Misc", freq:"triweekly", dow:6, weekOffset:2, lastDone:null},
  // MONTHLY
  {id:"mo_bat1",task:"Wash shower curtain",                          cat:"Bathroom", freq:"monthly", dow:1, nudgeDays:7,  lastDone:"2026-02-08"},
  {id:"mo_bat2",task:"Reorganize/throw out old stuff in bathroom cabinets", cat:"Bathroom", freq:"monthly", dow:1, nudgeDays:21, lastDone:"2025-11-01"},
  {id:"mo_win1",task:"Clean window tracks & framing",                cat:"Windows",  freq:"monthly", dow:6, nudgeDays:10, lastDone:null},
  {id:"mo_win2",task:"Wash interior window glass",                   cat:"Windows",  freq:"monthly", dow:6, nudgeDays:10, lastDone:null},
  {id:"mo_bed1",task:"Wash outer pillow covers (foam pillows)",      cat:"Bedroom",  freq:"monthly", dow:0, nudgeDays:7,  lastDone:null},
  {id:"mo_bed2",task:"Run comforter through dryer (20min high + 40min low)", cat:"Bedroom", freq:"monthly", dow:0, nudgeDays:21, lastDone:null},
  {id:"mo_bed3",task:"Wash duvet cover",                             cat:"Bedroom",  freq:"monthly", dow:0, nudgeDays:14, lastDone:null},
  {id:"mo_pan1",task:"Organize pantry / throw out old stuff",        cat:"Pantry",   freq:"monthly", dow:2, nudgeDays:7,  lastDone:"2026-02-04"},
  {id:"mo_lau1",task:"Deep clean washer/dryer exterior; run sanitizing cycle", cat:"Laundry", freq:"monthly", dow:4, nudgeDays:7, lastDone:null},
  {id:"mo_lau2",task:"Deep clean lint trap; sweep laundry floor; shake out mat; dust cobwebs", cat:"Laundry", freq:"monthly", dow:4, nudgeDays:7, lastDone:null},
  {id:"mo_lit1",task:"Wash cat toys & hair ties",                    cat:"Litter",   freq:"monthly", dow:4, nudgeDays:14, lastDone:null},
  {id:"mo_mis1",task:"Deep clean front door trim & threshold",       cat:"Misc",     freq:"monthly", dow:1, nudgeDays:14, lastDone:null},
  {id:"mo_mis2",task:"Dust curtains",                                cat:"Misc",     freq:"monthly", dow:0, nudgeDays:21, lastDone:"2026-02-04"},
  {id:"mo_mis3",task:"Wipe down wood frames of barstools & dining chairs", cat:"Misc", freq:"monthly", dow:0, nudgeDays:7, lastDone:null},
  {id:"mo_kit1",task:"Deep clean range hood (vent, light covers, removable parts)", cat:"Kitchen", freq:"monthly", dow:2, nudgeDays:21, lastDone:null},
  {id:"mo_kit2",task:"Wipe dishwasher control panel, door edge & gasket; spot clean interior", cat:"Kitchen", freq:"monthly", dow:2, nudgeDays:14, lastDone:null},
  {id:"mo_kit3",task:"Clean dishwasher filter",                      cat:"Kitchen",  freq:"monthly", dow:2, nudgeDays:14, lastDone:null},
  {id:"mo_kit4",task:"Reorganize/tidy kitchen cabinets & drawers",   cat:"Kitchen",  freq:"monthly", dow:2, nudgeDays:28, lastDone:"2025-12-01"},
  {id:"mo_kit5",task:"Wipe down silver part of bar",                 cat:"Kitchen",  freq:"monthly", dow:2, nudgeDays:5,  lastDone:null},
  {id:"mo_kit6",task:"Oil & condition cutting boards",               cat:"Kitchen",  freq:"monthly", dow:2, nudgeDays:5,  lastDone:"2026-01-15"},
  // EVERY 2 MONTHS
  {id:"e2m_f1",task:"Deep clean baseboards (scrub)",                 cat:"Floors",   freq:"2month", dow:1, nudgeDays:21, lastDone:null},
  {id:"e2m_f2",task:"Deep clean floor corners (scrub)",              cat:"Floors",   freq:"2month", dow:1, nudgeDays:42, lastDone:null},
  {id:"e2m_k1",task:"Deep clean kitchen trash can interior",         cat:"Kitchen",  freq:"2month", dow:2, nudgeDays:14, lastDone:null},
  // EVERY 3 MONTHS
  {id:"e3m_b1",task:"Deep clean shower tile & grout",                cat:"Bathroom", freq:"3month", dow:1, nudgeDays:14, lastDone:null},
  {id:"e3m_b2",task:"Deep clean showerhead",                         cat:"Bathroom", freq:"3month", dow:1, nudgeDays:14, lastDone:null},
  {id:"e3m_b3",task:"Deep clean tub",                                cat:"Bathroom", freq:"3month", dow:1, nudgeDays:14, lastDone:null},
  {id:"e3m_b4",task:"Vacuum shower fan",                             cat:"Bathroom", freq:"3month", dow:1, nudgeDays:56, lastDone:"2026-02-04"},
  {id:"e3m_b5",task:"Deep clean bathroom trash can",                 cat:"Bathroom", freq:"3month", dow:1, nudgeDays:35, lastDone:null},
  {id:"e3m_f1",task:"Vacuum/mop under rugs, couch, shoe cabinet, behind mirror, under fridge & stove", cat:"Floors", freq:"3month", dow:6, nudgeDays:21, lastDone:null},
  {id:"e3m_f2",task:"Deep clean green rug (baking soda)",            cat:"Floors",   freq:"3month", dow:6, nudgeDays:42, lastDone:null},
  {id:"e3m_f3",task:"Deep clean bedroom carpet (baking soda)",       cat:"Floors",   freq:"3month", dow:6, nudgeDays:63, lastDone:null},
  {id:"e3m_w1",task:"Clean window exteriors (remove cobwebs, wash glass under screens)", cat:"Windows", freq:"3month", dow:6, nudgeDays:35, lastDone:null},
  {id:"e3m_k1",task:"Deep clean fridge interior & shelving",         cat:"Kitchen",  freq:"3month", dow:2, nudgeDays:35, lastDone:null},
  {id:"e3m_k2",task:"Descale coffee maker",                          cat:"Kitchen",  freq:"3month", dow:2, nudgeDays:42, lastDone:"2026-01-15"},
  {id:"e3m_k3",task:"Wash toaster exterior & crumb tray; clean inner slots", cat:"Kitchen", freq:"3month", dow:2, nudgeDays:14, lastDone:null},
  {id:"e3m_k4",task:"Deep clean cutting boards w/ lemon + salt",     cat:"Kitchen",  freq:"3month", dow:2, nudgeDays:28, lastDone:null},
  {id:"e3m_k5",task:"Wipe down & deep clean stand mixer",            cat:"Kitchen",  freq:"3month", dow:2, nudgeDays:28, lastDone:null},
  // EVERY 6 MONTHS
  {id:"e6m_b1",task:"Replace toilet brush",                          cat:"Bathroom", freq:"6month", dow:1, nudgeDays:7,  lastDone:"2025-08-01"},
  {id:"e6m_b2",task:"Vacuum inside bathroom cabinets/drawers & wipe clean", cat:"Bathroom", freq:"6month", dow:1, nudgeDays:35, lastDone:null},
  {id:"e6m_bd1",task:"Wash mattress protector",                      cat:"Bedroom",  freq:"6month", dow:0, nudgeDays:70, lastDone:null},
  {id:"e6m_bd2",task:"Baking soda/vacuum mattress",                  cat:"Bedroom",  freq:"6month", dow:0, nudgeDays:77, lastDone:null},
  {id:"e6m_bd3",task:"Wash inner pillow covers + whole pillows (non-foam)", cat:"Bedroom", freq:"6month", dow:0, nudgeDays:84, lastDone:null},
  {id:"e6m_p1",task:"Vacuum inside pantry shelving & wipe down",     cat:"Pantry",   freq:"6month", dow:4, nudgeDays:28, lastDone:null},
  {id:"e6m_s1",task:"Deep clean bookshelves & dust books",           cat:"Shelving", freq:"6month", dow:0, nudgeDays:56, lastDone:null},
  {id:"e6m_c1",task:"Reorganize hallway closet",                     cat:"Closet",   freq:"6month", dow:4, nudgeDays:14, lastDone:"2026-02-04"},
  {id:"e6m_c2",task:"Deep clean shoe cabinet",                       cat:"Closet",   freq:"6month", dow:4, nudgeDays:42, lastDone:null},
  {id:"e6m_k1",task:"Clean oven broiler pan & oven interior",        cat:"Kitchen",  freq:"6month", dow:2, nudgeDays:56, lastDone:null},
  {id:"e6m_k2",task:"Run self-cleaning cycle on dishwasher",         cat:"Kitchen",  freq:"6month", dow:2, nudgeDays:63, lastDone:null},
  {id:"e6m_k3",task:"Deep clean inside kitchen cabinets/drawers",    cat:"Kitchen",  freq:"6month", dow:2, nudgeDays:70, lastDone:null},
  // ANNUALLY
  {id:"ann_w1",task:"Dust walls",                                    cat:"Walls",    freq:"annual", dow:1, nudgeDays:70,  lastDone:null},
  {id:"ann_w2",task:"Clean window screens",                          cat:"Windows",  freq:"annual", dow:6, nudgeDays:90,  lastDone:null},
  {id:"ann_k1",task:"Clean refrigerator condenser coils",            cat:"Kitchen",  freq:"annual", dow:2, nudgeDays:7,   lastDone:"2026-02-14"},
  {id:"ann_l1",task:"Replace litter box",                            cat:"Litter",   freq:"annual", dow:4, nudgeDays:28,  lastDone:"2025-02-01"},
  {id:"ann_c1",task:"Pull everything out of hallway closet & clean floors", cat:"Closet", freq:"annual", dow:4, nudgeDays:56, lastDone:null},
  {id:"ann_c2",task:"Go through clothing & donate",                  cat:"Closet",   freq:"annual", dow:0, nudgeDays:77,  lastDone:null},
  {id:"ann_c3",task:"Reorganize/refold clothing; vacuum closet shelving & drawers", cat:"Closet", freq:"annual", dow:0, nudgeDays:84, lastDone:null},
  {id:"ann_m1",task:"Clean heating vents",                           cat:"Misc",     freq:"annual", dow:1, nudgeDays:42,  lastDone:null},
  // EVERY 3 YEARS
  {id:"3yr_1",task:"Wash comforter",                                 cat:"Bedroom",  freq:"3year",  dow:0, nudgeDays:120, lastDone:null},
];
